# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from point_cloud_segmentation/EucledianClusterParamsRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EucledianClusterParamsRequest(genpy.Message):
  _md5sum = "71ff36b3407f0aba984bdadb41334b11"
  _type = "point_cloud_segmentation/EucledianClusterParamsRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 inlier_threshold
int32 max_iters
float32 leaf_size
int32 min_cluster_size
int32 max_cluster_size
float32 cluster_tolerance
"""
  __slots__ = ['inlier_threshold','max_iters','leaf_size','min_cluster_size','max_cluster_size','cluster_tolerance']
  _slot_types = ['float32','int32','float32','int32','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       inlier_threshold,max_iters,leaf_size,min_cluster_size,max_cluster_size,cluster_tolerance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EucledianClusterParamsRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.inlier_threshold is None:
        self.inlier_threshold = 0.
      if self.max_iters is None:
        self.max_iters = 0
      if self.leaf_size is None:
        self.leaf_size = 0.
      if self.min_cluster_size is None:
        self.min_cluster_size = 0
      if self.max_cluster_size is None:
        self.max_cluster_size = 0
      if self.cluster_tolerance is None:
        self.cluster_tolerance = 0.
    else:
      self.inlier_threshold = 0.
      self.max_iters = 0
      self.leaf_size = 0.
      self.min_cluster_size = 0
      self.max_cluster_size = 0
      self.cluster_tolerance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fif2if().pack(_x.inlier_threshold, _x.max_iters, _x.leaf_size, _x.min_cluster_size, _x.max_cluster_size, _x.cluster_tolerance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.inlier_threshold, _x.max_iters, _x.leaf_size, _x.min_cluster_size, _x.max_cluster_size, _x.cluster_tolerance,) = _get_struct_fif2if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fif2if().pack(_x.inlier_threshold, _x.max_iters, _x.leaf_size, _x.min_cluster_size, _x.max_cluster_size, _x.cluster_tolerance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.inlier_threshold, _x.max_iters, _x.leaf_size, _x.min_cluster_size, _x.max_cluster_size, _x.cluster_tolerance,) = _get_struct_fif2if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fif2if = None
def _get_struct_fif2if():
    global _struct_fif2if
    if _struct_fif2if is None:
        _struct_fif2if = struct.Struct("<fif2if")
    return _struct_fif2if
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from point_cloud_segmentation/EucledianClusterParamsResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EucledianClusterParamsResponse(genpy.Message):
  _md5sum = "358e233cde0c8a8bcfea4ce193f8fc15"
  _type = "point_cloud_segmentation/EucledianClusterParamsResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success

"""
  __slots__ = ['success']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EucledianClusterParamsResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
    else:
      self.success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class EucledianClusterParams(object):
  _type          = 'point_cloud_segmentation/EucledianClusterParams'
  _md5sum = 'd48de43a8ae594a80e6df131e81e4f77'
  _request_class  = EucledianClusterParamsRequest
  _response_class = EucledianClusterParamsResponse
