//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the urban_road_filter package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __urban_road_filter__LIDARFILTERSCONFIG_H__
#define __urban_road_filter__LIDARFILTERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace urban_road_filter
{
  class LidarFiltersConfigStatics;

  class LidarFiltersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(LidarFiltersConfig &config, const LidarFiltersConfig &max, const LidarFiltersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LidarFiltersConfig &config1, const LidarFiltersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LidarFiltersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LidarFiltersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LidarFiltersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LidarFiltersConfig &config) const = 0;
      virtual void getValue(const LidarFiltersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T LidarFiltersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T LidarFiltersConfig::* field;

      virtual void clamp(LidarFiltersConfig &config, const LidarFiltersConfig &max, const LidarFiltersConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LidarFiltersConfig &config1, const LidarFiltersConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LidarFiltersConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LidarFiltersConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LidarFiltersConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LidarFiltersConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LidarFiltersConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LidarFiltersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LidarFiltersConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<LidarFiltersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LidarFiltersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("fixed_frame"==(*_i)->name){fixed_frame = boost::any_cast<std::string>(val);}
        if("topic_name"==(*_i)->name){topic_name = boost::any_cast<std::string>(val);}
        if("x_zero_method"==(*_i)->name){x_zero_method = boost::any_cast<bool>(val);}
        if("z_zero_method"==(*_i)->name){z_zero_method = boost::any_cast<bool>(val);}
        if("star_shaped_method"==(*_i)->name){star_shaped_method = boost::any_cast<bool>(val);}
        if("blind_spots"==(*_i)->name){blind_spots = boost::any_cast<bool>(val);}
        if("xDirection"==(*_i)->name){xDirection = boost::any_cast<int>(val);}
        if("interval"==(*_i)->name){interval = boost::any_cast<double>(val);}
        if("curb_height"==(*_i)->name){curb_height = boost::any_cast<double>(val);}
        if("curb_points"==(*_i)->name){curb_points = boost::any_cast<int>(val);}
        if("beamZone"==(*_i)->name){beamZone = boost::any_cast<double>(val);}
        if("min_x"==(*_i)->name){min_x = boost::any_cast<double>(val);}
        if("max_x"==(*_i)->name){max_x = boost::any_cast<double>(val);}
        if("min_y"==(*_i)->name){min_y = boost::any_cast<double>(val);}
        if("max_y"==(*_i)->name){max_y = boost::any_cast<double>(val);}
        if("min_z"==(*_i)->name){min_z = boost::any_cast<double>(val);}
        if("max_z"==(*_i)->name){max_z = boost::any_cast<double>(val);}
        if("cylinder_deg_x"==(*_i)->name){cylinder_deg_x = boost::any_cast<double>(val);}
        if("cylinder_deg_z"==(*_i)->name){cylinder_deg_z = boost::any_cast<double>(val);}
        if("curb_slope_deg"==(*_i)->name){curb_slope_deg = boost::any_cast<double>(val);}
        if("kdev_param"==(*_i)->name){kdev_param = boost::any_cast<double>(val);}
        if("kdist_param"==(*_i)->name){kdist_param = boost::any_cast<double>(val);}
        if("starbeam_filter"==(*_i)->name){starbeam_filter = boost::any_cast<bool>(val);}
        if("dmin_param"==(*_i)->name){dmin_param = boost::any_cast<int>(val);}
        if("simple_poly_allow"==(*_i)->name){simple_poly_allow = boost::any_cast<bool>(val);}
        if("poly_s_param"==(*_i)->name){poly_s_param = boost::any_cast<double>(val);}
        if("poly_z_manual"==(*_i)->name){poly_z_manual = boost::any_cast<double>(val);}
        if("poly_z_avg_allow"==(*_i)->name){poly_z_avg_allow = boost::any_cast<bool>(val);}
      }
    }

    std::string fixed_frame;
std::string topic_name;
bool x_zero_method;
bool z_zero_method;
bool star_shaped_method;
bool blind_spots;
int xDirection;
double interval;
double curb_height;
int curb_points;
double beamZone;
double min_x;
double max_x;
double min_y;
double max_y;
double min_z;
double max_z;
double cylinder_deg_x;
double cylinder_deg_z;
double curb_slope_deg;
double kdev_param;
double kdist_param;
bool starbeam_filter;
int dmin_param;
bool simple_poly_allow;
double poly_s_param;
double poly_z_manual;
bool poly_z_avg_allow;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string fixed_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string topic_name;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool x_zero_method;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool z_zero_method;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool star_shaped_method;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool blind_spots;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int xDirection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double interval;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double curb_height;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int curb_points;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double beamZone;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cylinder_deg_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cylinder_deg_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double curb_slope_deg;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kdev_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kdist_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool starbeam_filter;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int dmin_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool simple_poly_allow;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double poly_s_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double poly_z_manual;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool poly_z_avg_allow;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LidarFiltersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LidarFiltersConfig &__max__ = __getMax__();
      const LidarFiltersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LidarFiltersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LidarFiltersConfig &__getDefault__();
    static const LidarFiltersConfig &__getMax__();
    static const LidarFiltersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const LidarFiltersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void LidarFiltersConfig::ParamDescription<std::string>::clamp(LidarFiltersConfig &config, const LidarFiltersConfig &max, const LidarFiltersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class LidarFiltersConfigStatics
  {
    friend class LidarFiltersConfig;

    LidarFiltersConfigStatics()
    {
LidarFiltersConfig::GroupDescription<LidarFiltersConfig::DEFAULT, LidarFiltersConfig> Default("Default", "", 0, 0, true, &LidarFiltersConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fixed_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fixed_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fixed_frame = "left_os1/os1_lidar";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<std::string>("fixed_frame", "str", 0, "Fixed frame. (Restart needed if it changes.)", "", &LidarFiltersConfig::fixed_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<std::string>("fixed_frame", "str", 0, "Fixed frame. (Restart needed if it changes.)", "", &LidarFiltersConfig::fixed_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.topic_name = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.topic_name = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.topic_name = "/left_os1/os1_cloud_node/points";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<std::string>("topic_name", "str", 0, "(Restart needed if it changes.)", "", &LidarFiltersConfig::topic_name)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<std::string>("topic_name", "str", 0, "(Restart needed if it changes.)", "", &LidarFiltersConfig::topic_name)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_zero_method = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_zero_method = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_zero_method = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("x_zero_method", "bool", 0, "x zero method.", "", &LidarFiltersConfig::x_zero_method)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("x_zero_method", "bool", 0, "x zero method.", "", &LidarFiltersConfig::x_zero_method)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_zero_method = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_zero_method = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_zero_method = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("z_zero_method", "bool", 0, "z zero method.", "", &LidarFiltersConfig::z_zero_method)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("z_zero_method", "bool", 0, "z zero method.", "", &LidarFiltersConfig::z_zero_method)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.star_shaped_method = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.star_shaped_method = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.star_shaped_method = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("star_shaped_method", "bool", 0, "star shaped method", "", &LidarFiltersConfig::star_shaped_method)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("star_shaped_method", "bool", 0, "star shaped method", "", &LidarFiltersConfig::star_shaped_method)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.blind_spots = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.blind_spots = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.blind_spots = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("blind_spots", "bool", 0, "Filtering blind spots.", "", &LidarFiltersConfig::blind_spots)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("blind_spots", "bool", 0, "Filtering blind spots.", "", &LidarFiltersConfig::blind_spots)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.xDirection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.xDirection = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.xDirection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<int>("xDirection", "int", 0, "Filtering blind spots in  (+-,+,-) X direction.", "{'enum': [{'name': 'bothX', 'type': 'int', 'value': 0, 'srcline': 23, 'srcfile': '/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg', 'description': 'Filtering in both negative and positive direction along the Lidars X axis', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'positiveX', 'type': 'int', 'value': 1, 'srcline': 24, 'srcfile': '/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg', 'description': 'Filtering only in +X .', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'negativeX', 'type': 'int', 'value': 2, 'srcline': 25, 'srcfile': '/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg', 'description': 'Filtering only in -X.', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Filtering blind spots in  (+-,+,-) X direction.'}", &LidarFiltersConfig::xDirection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<int>("xDirection", "int", 0, "Filtering blind spots in  (+-,+,-) X direction.", "{'enum': [{'name': 'bothX', 'type': 'int', 'value': 0, 'srcline': 23, 'srcfile': '/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg', 'description': 'Filtering in both negative and positive direction along the Lidars X axis', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'positiveX', 'type': 'int', 'value': 1, 'srcline': 24, 'srcfile': '/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg', 'description': 'Filtering only in +X .', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'negativeX', 'type': 'int', 'value': 2, 'srcline': 25, 'srcfile': '/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg', 'description': 'Filtering only in -X.', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Filtering blind spots in  (+-,+,-) X direction.'}", &LidarFiltersConfig::xDirection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.interval = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.interval = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.interval = 0.18;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("interval", "double", 0, "LIDAR's vertical resolution", "", &LidarFiltersConfig::interval)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("interval", "double", 0, "LIDAR's vertical resolution", "", &LidarFiltersConfig::interval)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.curb_height = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.curb_height = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.curb_height = 0.05;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("curb_height", "double", 0, "Estimated minimum height of the curb.[m]", "", &LidarFiltersConfig::curb_height)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("curb_height", "double", 0, "Estimated minimum height of the curb.[m]", "", &LidarFiltersConfig::curb_height)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.curb_points = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.curb_points = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.curb_points = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<int>("curb_points", "int", 0, "Estimated number of points on the curb.[pcs]", "", &LidarFiltersConfig::curb_points)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<int>("curb_points", "int", 0, "Estimated number of points on the curb.[pcs]", "", &LidarFiltersConfig::curb_points)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.beamZone = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.beamZone = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.beamZone = 30.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("beamZone", "double", 0, "Width of the beam zone.[deg]", "", &LidarFiltersConfig::beamZone)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("beamZone", "double", 0, "Width of the beam zone.[deg]", "", &LidarFiltersConfig::beamZone)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_x = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_x = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("min_x", "double", 0, "Size of the examined area: Min X [m].", "", &LidarFiltersConfig::min_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("min_x", "double", 0, "Size of the examined area: Min X [m].", "", &LidarFiltersConfig::min_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_x = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_x = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_x = 30.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("max_x", "double", 0, "Size of the examined area:: Max X [m].", "", &LidarFiltersConfig::max_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("max_x", "double", 0, "Size of the examined area:: Max X [m].", "", &LidarFiltersConfig::max_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_y = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_y = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_y = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("min_y", "double", 0, "Size of the examined area: Min Y [m].", "", &LidarFiltersConfig::min_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("min_y", "double", 0, "Size of the examined area: Min Y [m].", "", &LidarFiltersConfig::min_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_y = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_y = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("max_y", "double", 0, "Size of the examined area: Max Y [m].", "", &LidarFiltersConfig::max_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("max_y", "double", 0, "Size of the examined area: Max Y [m].", "", &LidarFiltersConfig::max_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_z = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_z = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_z = -3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("min_z", "double", 0, "Size of the examined area: Min Z [m]. ", "", &LidarFiltersConfig::min_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("min_z", "double", 0, "Size of the examined area: Min Z [m]. ", "", &LidarFiltersConfig::min_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_z = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_z = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_z = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("max_z", "double", 0, "Size of the examined area: Max Z [m].", "", &LidarFiltersConfig::max_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("max_z", "double", 0, "Size of the examined area: Max Z [m].", "", &LidarFiltersConfig::max_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cylinder_deg_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cylinder_deg_x = 180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cylinder_deg_x = 150.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("cylinder_deg_x", "double", 0, "The included angle of the examined triangle(three point)[deg]. - x_zero_method", "", &LidarFiltersConfig::cylinder_deg_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("cylinder_deg_x", "double", 0, "The included angle of the examined triangle(three point)[deg]. - x_zero_method", "", &LidarFiltersConfig::cylinder_deg_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cylinder_deg_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cylinder_deg_z = 180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cylinder_deg_z = 140.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("cylinder_deg_z", "double", 0, "The included angle of the examined triangle(two vectors)[deg]. - z_zero_method", "", &LidarFiltersConfig::cylinder_deg_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("cylinder_deg_z", "double", 0, "The included angle of the examined triangle(two vectors)[deg]. - z_zero_method", "", &LidarFiltersConfig::cylinder_deg_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.curb_slope_deg = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.curb_slope_deg = 180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.curb_slope_deg = 50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("curb_slope_deg", "double", 0, "Radial threshold [deg]. - star_shaped_method", "", &LidarFiltersConfig::curb_slope_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("curb_slope_deg", "double", 0, "Radial threshold [deg]. - star_shaped_method", "", &LidarFiltersConfig::curb_slope_deg)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kdev_param = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kdev_param = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kdev_param = 1.225;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("kdev_param", "double", 0, "Disperion coefficient", "", &LidarFiltersConfig::kdev_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("kdev_param", "double", 0, "Disperion coefficient", "", &LidarFiltersConfig::kdev_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kdist_param = 0.4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kdist_param = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kdist_param = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("kdist_param", "double", 0, "Distance coefficient", "", &LidarFiltersConfig::kdist_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("kdist_param", "double", 0, "Distance coefficient", "", &LidarFiltersConfig::kdist_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.starbeam_filter = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.starbeam_filter = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.starbeam_filter = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("starbeam_filter", "bool", 0, "Use rectangular beams for detection instead of the whole sectors (StarShaped)", "", &LidarFiltersConfig::starbeam_filter)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("starbeam_filter", "bool", 0, "Use rectangular beams for detection instead of the whole sectors (StarShaped)", "", &LidarFiltersConfig::starbeam_filter)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dmin_param = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dmin_param = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dmin_param = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<int>("dmin_param", "int", 0, "Min number of points for dispersion", "", &LidarFiltersConfig::dmin_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<int>("dmin_param", "int", 0, "Min number of points for dispersion", "", &LidarFiltersConfig::dmin_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.simple_poly_allow = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.simple_poly_allow = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.simple_poly_allow = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("simple_poly_allow", "bool", 0, "Use simplified polygon (height data will be lost!)", "", &LidarFiltersConfig::simple_poly_allow)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("simple_poly_allow", "bool", 0, "Use simplified polygon (height data will be lost!)", "", &LidarFiltersConfig::simple_poly_allow)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.poly_s_param = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.poly_s_param = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.poly_s_param = 0.7;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("poly_s_param", "double", 0, "Coefficient of polygon simplification", "", &LidarFiltersConfig::poly_s_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("poly_s_param", "double", 0, "Coefficient of polygon simplification", "", &LidarFiltersConfig::poly_s_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.poly_z_manual = -5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.poly_z_manual = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.poly_z_manual = -1.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("poly_z_manual", "double", 0, "Set a constant polygon height", "", &LidarFiltersConfig::poly_z_manual)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<double>("poly_z_manual", "double", 0, "Set a constant polygon height", "", &LidarFiltersConfig::poly_z_manual)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.poly_z_avg_allow = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.poly_z_avg_allow = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.poly_z_avg_allow = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("poly_z_avg_allow", "bool", 0, "Set polygon height to average value", "", &LidarFiltersConfig::poly_z_avg_allow)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LidarFiltersConfig::AbstractParamDescriptionConstPtr(new LidarFiltersConfig::ParamDescription<bool>("poly_z_avg_allow", "bool", 0, "Set polygon height to average value", "", &LidarFiltersConfig::poly_z_avg_allow)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LidarFiltersConfig::AbstractGroupDescriptionConstPtr(new LidarFiltersConfig::GroupDescription<LidarFiltersConfig::DEFAULT, LidarFiltersConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<LidarFiltersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<LidarFiltersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LidarFiltersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LidarFiltersConfig __max__;
    LidarFiltersConfig __min__;
    LidarFiltersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LidarFiltersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LidarFiltersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LidarFiltersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const LidarFiltersConfig &LidarFiltersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const LidarFiltersConfig &LidarFiltersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const LidarFiltersConfig &LidarFiltersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<LidarFiltersConfig::AbstractParamDescriptionConstPtr> &LidarFiltersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LidarFiltersConfig::AbstractGroupDescriptionConstPtr> &LidarFiltersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LidarFiltersConfigStatics *LidarFiltersConfig::__get_statics__()
  {
    const static LidarFiltersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LidarFiltersConfigStatics::get_instance();

    return statics;
  }

//#line 23 "/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg"
      const int LidarFilters_bothX = 0;
//#line 24 "/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg"
      const int LidarFilters_positiveX = 1;
//#line 25 "/home/kai/catkin_ws/src/urban_road_filter-main/cfg/LidarFilters.cfg"
      const int LidarFilters_negativeX = 2;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LIDARFILTERSRECONFIGURATOR_H__
