// Generated by gencpp from file point_cloud_segmentation/BaseSegmentationParams.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_BASESEGMENTATIONPARAMS_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_BASESEGMENTATIONPARAMS_H

#include <ros/service_traits.h>


#include <point_cloud_segmentation/BaseSegmentationParamsRequest.h>
#include <point_cloud_segmentation/BaseSegmentationParamsResponse.h>


namespace point_cloud_segmentation
{

struct BaseSegmentationParams
{

typedef BaseSegmentationParamsRequest Request;
typedef BaseSegmentationParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BaseSegmentationParams
} // namespace point_cloud_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_cloud_segmentation::BaseSegmentationParams > {
  static const char* value()
  {
    return "cc22b1ef630d46c7f989e768fadb8c56";
  }

  static const char* value(const ::point_cloud_segmentation::BaseSegmentationParams&) { return value(); }
};

template<>
struct DataType< ::point_cloud_segmentation::BaseSegmentationParams > {
  static const char* value()
  {
    return "point_cloud_segmentation/BaseSegmentationParams";
  }

  static const char* value(const ::point_cloud_segmentation::BaseSegmentationParams&) { return value(); }
};


// service_traits::MD5Sum< ::point_cloud_segmentation::BaseSegmentationParamsRequest> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::BaseSegmentationParams >
template<>
struct MD5Sum< ::point_cloud_segmentation::BaseSegmentationParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::BaseSegmentationParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::BaseSegmentationParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::BaseSegmentationParamsRequest> should match
// service_traits::DataType< ::point_cloud_segmentation::BaseSegmentationParams >
template<>
struct DataType< ::point_cloud_segmentation::BaseSegmentationParamsRequest>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::BaseSegmentationParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::BaseSegmentationParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_cloud_segmentation::BaseSegmentationParamsResponse> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::BaseSegmentationParams >
template<>
struct MD5Sum< ::point_cloud_segmentation::BaseSegmentationParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::BaseSegmentationParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::BaseSegmentationParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::BaseSegmentationParamsResponse> should match
// service_traits::DataType< ::point_cloud_segmentation::BaseSegmentationParams >
template<>
struct DataType< ::point_cloud_segmentation::BaseSegmentationParamsResponse>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::BaseSegmentationParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::BaseSegmentationParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_BASESEGMENTATIONPARAMS_H
