// Generated by gencpp from file point_cloud_segmentation/ChangeSegmentationMethodResponse.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHODRESPONSE_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHODRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_cloud_segmentation
{
template <class ContainerAllocator>
struct ChangeSegmentationMethodResponse_
{
  typedef ChangeSegmentationMethodResponse_<ContainerAllocator> Type;

  ChangeSegmentationMethodResponse_()
    : success(false)  {
    }
  ChangeSegmentationMethodResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeSegmentationMethodResponse_

typedef ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<std::allocator<void> > ChangeSegmentationMethodResponse;

typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodResponse > ChangeSegmentationMethodResponsePtr;
typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodResponse const> ChangeSegmentationMethodResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator1> & lhs, const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator1> & lhs, const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace point_cloud_segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_segmentation/ChangeSegmentationMethodResponse";
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success \n"
"\n"
;
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeSegmentationMethodResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_cloud_segmentation::ChangeSegmentationMethodResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHODRESPONSE_H
