// Generated by gencpp from file point_cloud_segmentation/ChangeSegmentationMethod.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHOD_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHOD_H

#include <ros/service_traits.h>


#include <point_cloud_segmentation/ChangeSegmentationMethodRequest.h>
#include <point_cloud_segmentation/ChangeSegmentationMethodResponse.h>


namespace point_cloud_segmentation
{

struct ChangeSegmentationMethod
{

typedef ChangeSegmentationMethodRequest Request;
typedef ChangeSegmentationMethodResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeSegmentationMethod
} // namespace point_cloud_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethod > {
  static const char* value()
  {
    return "0291f58b1b9fc66d8f5c8659995fd485";
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethod&) { return value(); }
};

template<>
struct DataType< ::point_cloud_segmentation::ChangeSegmentationMethod > {
  static const char* value()
  {
    return "point_cloud_segmentation/ChangeSegmentationMethod";
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethod&) { return value(); }
};


// service_traits::MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethodRequest> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethod >
template<>
struct MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethodRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethod >::value();
  }
  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::ChangeSegmentationMethodRequest> should match
// service_traits::DataType< ::point_cloud_segmentation::ChangeSegmentationMethod >
template<>
struct DataType< ::point_cloud_segmentation::ChangeSegmentationMethodRequest>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::ChangeSegmentationMethod >::value();
  }
  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethodResponse> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethod >
template<>
struct MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethodResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethod >::value();
  }
  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::ChangeSegmentationMethodResponse> should match
// service_traits::DataType< ::point_cloud_segmentation::ChangeSegmentationMethod >
template<>
struct DataType< ::point_cloud_segmentation::ChangeSegmentationMethodResponse>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::ChangeSegmentationMethod >::value();
  }
  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHOD_H
