// Generated by gencpp from file point_cloud_segmentation/ChangeSegmentationMethodRequest.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHODREQUEST_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHODREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_cloud_segmentation
{
template <class ContainerAllocator>
struct ChangeSegmentationMethodRequest_
{
  typedef ChangeSegmentationMethodRequest_<ContainerAllocator> Type;

  ChangeSegmentationMethodRequest_()
    : segmentation_method()  {
    }
  ChangeSegmentationMethodRequest_(const ContainerAllocator& _alloc)
    : segmentation_method(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _segmentation_method_type;
  _segmentation_method_type segmentation_method;





  typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeSegmentationMethodRequest_

typedef ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<std::allocator<void> > ChangeSegmentationMethodRequest;

typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodRequest > ChangeSegmentationMethodRequestPtr;
typedef boost::shared_ptr< ::point_cloud_segmentation::ChangeSegmentationMethodRequest const> ChangeSegmentationMethodRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator1> & lhs, const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator2> & rhs)
{
  return lhs.segmentation_method == rhs.segmentation_method;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator1> & lhs, const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace point_cloud_segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a78fc2bf16f4378a3aaddc60b5dcbf3";
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a78fc2bf16f4378ULL;
  static const uint64_t static_value2 = 0xa3aaddc60b5dcbf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_segmentation/ChangeSegmentationMethodRequest";
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string segmentation_method \n"
;
  }

  static const char* value(const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.segmentation_method);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeSegmentationMethodRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_cloud_segmentation::ChangeSegmentationMethodRequest_<ContainerAllocator>& v)
  {
    s << indent << "segmentation_method: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.segmentation_method);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_CHANGESEGMENTATIONMETHODREQUEST_H
