// Generated by gencpp from file point_cloud_segmentation/EucledianClusterParamsRequest.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_EUCLEDIANCLUSTERPARAMSREQUEST_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_EUCLEDIANCLUSTERPARAMSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_cloud_segmentation
{
template <class ContainerAllocator>
struct EucledianClusterParamsRequest_
{
  typedef EucledianClusterParamsRequest_<ContainerAllocator> Type;

  EucledianClusterParamsRequest_()
    : inlier_threshold(0.0)
    , max_iters(0)
    , leaf_size(0.0)
    , min_cluster_size(0)
    , max_cluster_size(0)
    , cluster_tolerance(0.0)  {
    }
  EucledianClusterParamsRequest_(const ContainerAllocator& _alloc)
    : inlier_threshold(0.0)
    , max_iters(0)
    , leaf_size(0.0)
    , min_cluster_size(0)
    , max_cluster_size(0)
    , cluster_tolerance(0.0)  {
  (void)_alloc;
    }



   typedef float _inlier_threshold_type;
  _inlier_threshold_type inlier_threshold;

   typedef int32_t _max_iters_type;
  _max_iters_type max_iters;

   typedef float _leaf_size_type;
  _leaf_size_type leaf_size;

   typedef int32_t _min_cluster_size_type;
  _min_cluster_size_type min_cluster_size;

   typedef int32_t _max_cluster_size_type;
  _max_cluster_size_type max_cluster_size;

   typedef float _cluster_tolerance_type;
  _cluster_tolerance_type cluster_tolerance;





  typedef boost::shared_ptr< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EucledianClusterParamsRequest_

typedef ::point_cloud_segmentation::EucledianClusterParamsRequest_<std::allocator<void> > EucledianClusterParamsRequest;

typedef boost::shared_ptr< ::point_cloud_segmentation::EucledianClusterParamsRequest > EucledianClusterParamsRequestPtr;
typedef boost::shared_ptr< ::point_cloud_segmentation::EucledianClusterParamsRequest const> EucledianClusterParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator1> & lhs, const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.inlier_threshold == rhs.inlier_threshold &&
    lhs.max_iters == rhs.max_iters &&
    lhs.leaf_size == rhs.leaf_size &&
    lhs.min_cluster_size == rhs.min_cluster_size &&
    lhs.max_cluster_size == rhs.max_cluster_size &&
    lhs.cluster_tolerance == rhs.cluster_tolerance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator1> & lhs, const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace point_cloud_segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71ff36b3407f0aba984bdadb41334b11";
  }

  static const char* value(const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71ff36b3407f0abaULL;
  static const uint64_t static_value2 = 0x984bdadb41334b11ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_segmentation/EucledianClusterParamsRequest";
  }

  static const char* value(const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 inlier_threshold\n"
"int32 max_iters\n"
"float32 leaf_size\n"
"int32 min_cluster_size\n"
"int32 max_cluster_size\n"
"float32 cluster_tolerance\n"
;
  }

  static const char* value(const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inlier_threshold);
      stream.next(m.max_iters);
      stream.next(m.leaf_size);
      stream.next(m.min_cluster_size);
      stream.next(m.max_cluster_size);
      stream.next(m.cluster_tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EucledianClusterParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_cloud_segmentation::EucledianClusterParamsRequest_<ContainerAllocator>& v)
  {
    s << indent << "inlier_threshold: ";
    Printer<float>::stream(s, indent + "  ", v.inlier_threshold);
    s << indent << "max_iters: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_iters);
    s << indent << "leaf_size: ";
    Printer<float>::stream(s, indent + "  ", v.leaf_size);
    s << indent << "min_cluster_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.min_cluster_size);
    s << indent << "max_cluster_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_cluster_size);
    s << indent << "cluster_tolerance: ";
    Printer<float>::stream(s, indent + "  ", v.cluster_tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_EUCLEDIANCLUSTERPARAMSREQUEST_H
