// Generated by gencpp from file point_cloud_segmentation/RegionGrowingSegParams.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_REGIONGROWINGSEGPARAMS_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_REGIONGROWINGSEGPARAMS_H

#include <ros/service_traits.h>


#include <point_cloud_segmentation/RegionGrowingSegParamsRequest.h>
#include <point_cloud_segmentation/RegionGrowingSegParamsResponse.h>


namespace point_cloud_segmentation
{

struct RegionGrowingSegParams
{

typedef RegionGrowingSegParamsRequest Request;
typedef RegionGrowingSegParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegionGrowingSegParams
} // namespace point_cloud_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParams > {
  static const char* value()
  {
    return "38336d175b585d3b451f02cd0a82d0d1";
  }

  static const char* value(const ::point_cloud_segmentation::RegionGrowingSegParams&) { return value(); }
};

template<>
struct DataType< ::point_cloud_segmentation::RegionGrowingSegParams > {
  static const char* value()
  {
    return "point_cloud_segmentation/RegionGrowingSegParams";
  }

  static const char* value(const ::point_cloud_segmentation::RegionGrowingSegParams&) { return value(); }
};


// service_traits::MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParamsRequest> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParams >
template<>
struct MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::RegionGrowingSegParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::RegionGrowingSegParamsRequest> should match
// service_traits::DataType< ::point_cloud_segmentation::RegionGrowingSegParams >
template<>
struct DataType< ::point_cloud_segmentation::RegionGrowingSegParamsRequest>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::RegionGrowingSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::RegionGrowingSegParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParamsResponse> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParams >
template<>
struct MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::RegionGrowingSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::RegionGrowingSegParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::RegionGrowingSegParamsResponse> should match
// service_traits::DataType< ::point_cloud_segmentation::RegionGrowingSegParams >
template<>
struct DataType< ::point_cloud_segmentation::RegionGrowingSegParamsResponse>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::RegionGrowingSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::RegionGrowingSegParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_REGIONGROWINGSEGPARAMS_H
