// Generated by gencpp from file point_cloud_segmentation/SegmentScene.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_SEGMENTSCENE_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_SEGMENTSCENE_H

#include <ros/service_traits.h>


#include <point_cloud_segmentation/SegmentSceneRequest.h>
#include <point_cloud_segmentation/SegmentSceneResponse.h>


namespace point_cloud_segmentation
{

struct SegmentScene
{

typedef SegmentSceneRequest Request;
typedef SegmentSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SegmentScene
} // namespace point_cloud_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_cloud_segmentation::SegmentScene > {
  static const char* value()
  {
    return "d67a831539406124d35c176a9550dd53";
  }

  static const char* value(const ::point_cloud_segmentation::SegmentScene&) { return value(); }
};

template<>
struct DataType< ::point_cloud_segmentation::SegmentScene > {
  static const char* value()
  {
    return "point_cloud_segmentation/SegmentScene";
  }

  static const char* value(const ::point_cloud_segmentation::SegmentScene&) { return value(); }
};


// service_traits::MD5Sum< ::point_cloud_segmentation::SegmentSceneRequest> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::SegmentScene >
template<>
struct MD5Sum< ::point_cloud_segmentation::SegmentSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::SegmentScene >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SegmentSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::SegmentSceneRequest> should match
// service_traits::DataType< ::point_cloud_segmentation::SegmentScene >
template<>
struct DataType< ::point_cloud_segmentation::SegmentSceneRequest>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::SegmentScene >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SegmentSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_cloud_segmentation::SegmentSceneResponse> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::SegmentScene >
template<>
struct MD5Sum< ::point_cloud_segmentation::SegmentSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::SegmentScene >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SegmentSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::SegmentSceneResponse> should match
// service_traits::DataType< ::point_cloud_segmentation::SegmentScene >
template<>
struct DataType< ::point_cloud_segmentation::SegmentSceneResponse>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::SegmentScene >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SegmentSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_SEGMENTSCENE_H
