// Generated by gencpp from file point_cloud_segmentation/SuperClusteringSegParams.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SEGMENTATION_MESSAGE_SUPERCLUSTERINGSEGPARAMS_H
#define POINT_CLOUD_SEGMENTATION_MESSAGE_SUPERCLUSTERINGSEGPARAMS_H

#include <ros/service_traits.h>


#include <point_cloud_segmentation/SuperClusteringSegParamsRequest.h>
#include <point_cloud_segmentation/SuperClusteringSegParamsResponse.h>


namespace point_cloud_segmentation
{

struct SuperClusteringSegParams
{

typedef SuperClusteringSegParamsRequest Request;
typedef SuperClusteringSegParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SuperClusteringSegParams
} // namespace point_cloud_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParams > {
  static const char* value()
  {
    return "856257f6ec8c4470a3201718c51e1da6";
  }

  static const char* value(const ::point_cloud_segmentation::SuperClusteringSegParams&) { return value(); }
};

template<>
struct DataType< ::point_cloud_segmentation::SuperClusteringSegParams > {
  static const char* value()
  {
    return "point_cloud_segmentation/SuperClusteringSegParams";
  }

  static const char* value(const ::point_cloud_segmentation::SuperClusteringSegParams&) { return value(); }
};


// service_traits::MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParamsRequest> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParams >
template<>
struct MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SuperClusteringSegParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::SuperClusteringSegParamsRequest> should match
// service_traits::DataType< ::point_cloud_segmentation::SuperClusteringSegParams >
template<>
struct DataType< ::point_cloud_segmentation::SuperClusteringSegParamsRequest>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::SuperClusteringSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SuperClusteringSegParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParamsResponse> should match
// service_traits::MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParams >
template<>
struct MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_cloud_segmentation::SuperClusteringSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SuperClusteringSegParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_cloud_segmentation::SuperClusteringSegParamsResponse> should match
// service_traits::DataType< ::point_cloud_segmentation::SuperClusteringSegParams >
template<>
struct DataType< ::point_cloud_segmentation::SuperClusteringSegParamsResponse>
{
  static const char* value()
  {
    return DataType< ::point_cloud_segmentation::SuperClusteringSegParams >::value();
  }
  static const char* value(const ::point_cloud_segmentation::SuperClusteringSegParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_CLOUD_SEGMENTATION_MESSAGE_SUPERCLUSTERINGSEGPARAMS_H
